services:
  bdd:
    image: mysql  # Utilisation de la version Long Term Support
    restart: always     
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: MarsAI-database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql 
    healthcheck:
      test: ["CMD","mysql", "-uuser","-puser","--database=MarsAI-database"]
      retries: 2
      start_period: 10s
    
  pma:
    image: phpmyadmin
    environment:
      PMA_HOST: bdd
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - bdd

  front:
    image: luzrivera/mars-front
    # ports is NOT HERE look compose.dev.yaml and compose.prod.yaml
    # build is NOT HERE look compose.dev.yaml and compose.prod.yaml


  back:
    image: luzrivera/mars-back
    build: ./back-end
    ports:
      - "3004:3000"
    environment:
      - DB_NAME=MarsAI-database
      - DB_USER=user
      - DB_PASS=user
      - DB_HOST=bdd
      - DB_PORT=3306
      - PORT=3000
      # - FRONTEND_URL=http://grpfour.whiletrue.fr 
      - NODE_ENV=production
      - RESEND_API_KEY=re_cW54KG7F_AwyqtHCuakGBzCmZMfdamhj6
      - JWT_SECRET=secret123
      - SMTP_HOST=smtp.mailtrap.io
      - SMTP_PORT=587
      - SMTP_USER=resend
      - SMTP_PASS=re_cW54KG7F_AwyqtHCuakGBzCmZMfdamhj6
      - SMTP_FROM=noreply@marsai.fr
      - SMTP_FROM=onboarding@resend.dev
      - API_KEY=AIzaSyB5clZNC7q8e5s5S6wSn_zg6MT9WCjGt7g
      - RATELIMIT=500
    depends_on:
      bdd :
        condition: service_healthy

volumes:
  db_data: