services:
  bdd:
    image: mysql  # Utilisation de la version Long Term Support
    restart: always     
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: MarsAI-database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql 
    healthcheck:
      test: ["CMD","mysql", "-uuser","-puser","--database=MarsAI-database"]
      retries: 2
      start_period: 10s
    
  pma:
    image: phpmyadmin
    environment:
      PMA_HOST: bdd
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - bdd

  front:
    image: luzrivera/mars-front
    build: ./front-end
    ports:
      - "8004:80"
    env_file:
      - ./front-end/.env.prod


  back:
    image: luzrivera/mars-back
    build: ./back-end
    ports:
      - "3004:3000"
    env_file:
      - ./back-end/.env.prod
    depends_on:
      bdd :
        condition: service_healthy

volumes:
  db_data: