import { Film } from "../models/film.mjs";

export async function filmSeed() {
  await Film.bulkCreate([
    {
      candidature_id: 1,
      user_id: 1,
      collaborateur: "Jean Dupont",
      title: "L’OMBRE NUMÉRIQUE",
      duration: 12.5,
      subtitle: "Quand l’IA observe l’humain",
      description: "Un court-métrage sur la surveillance et la liberté à l’ère de l’IA.",
      category: "Science-fiction",
      film_url: "https://example.com/films/ombre-numerique.mp4",
      poster_url: "https://picsum.photos/seed/film1/600/900",
      outil_Ai: "Midjourney",
      generate_Ai: "full_ai",
      selected: false,
    },
    {
      candidature_id: 2,
      user_id: 1,
      collaborateur: "Marie Laurent",
      title: "VISAGES SYNTHÉTIQUES",
      duration: 9.8,
      subtitle: "Portraits artificiels",
      description: "Des visages générés par IA questionnent l’identité humaine.",
      category: "Documentaire",
      film_url: "https://example.com/films/visages-synthetiques.mp4",
      poster_url: "https://picsum.photos/seed/film2/600/900",
      outil_Ai: "DALL·E",
      generate_Ai: "hybrid",
      selected: false,
    },
    {
      candidature_id: 3,
      user_id: 2,
      collaborateur: "Lucas Martin",
      title: "CODE MÈRE",
      duration: 15.2,
      subtitle: "La naissance d’une conscience",
      description: "Une IA prend conscience d’elle-même dans un data center isolé.",
      category: "Animation",
      film_url: "https://example.com/films/code-mere.mp4",
      poster_url: "https://picsum.photos/seed/film3/600/900",
      outil_Ai: "Runway",
      generate_Ai: "full_ai",
      selected: true,
    },
    {
      candidature_id: 4,
      user_id: 2,
      collaborateur: "Sofia Perez",
      title: "ÉCHO MÉCANIQUE",
      duration: 11.0,
      subtitle: "Souvenirs artificiels",
      description: "Une ville racontée par les données laissées par ses habitants.",
      category: "Drame",
      film_url: "https://example.com/films/echo-mecanique.mp4",
      poster_url: "https://picsum.photos/seed/film4/600/900",
      outil_Ai: "Stable Diffusion",
      generate_Ai: "hybrid",
      selected: false,
    },
    {
      candidature_id: 5,
      user_id: 3,
      collaborateur: "Ahmed Benali",
      title: "AU-DELÀ DU SIGNAL",
      duration: 13.4,
      subtitle: "Silence algorithmique",
      description: "Une expérience sonore créée à partir de signaux abandonnés.",
      category: "Expérimental",
      film_url: "https://example.com/films/au-dela-du-signal.mp4",
      poster_url: "https://picsum.photos/seed/film5/600/900",
      outil_Ai: "AIVA",
      generate_Ai: "full_ai",
      selected: false,
    },
    {
      candidature_id: 6,
      user_id: 3,
      collaborateur: "Clara Nguyen",
      title: "RÊVES DE SILICIUM",
      duration: 10.1,
      subtitle: "Songes artificiels",
      description: "Une IA tente de recréer des rêves humains à partir de données.",
      category: "Fantastique",
      film_url: "https://example.com/films/reves-de-silicium.mp4",
      poster_url: "https://picsum.photos/seed/film6/600/900",
      outil_Ai: "Midjourney",
      generate_Ai: "hybrid",
      selected: true,
    },
    {
      candidature_id: 7,
      user_id: 4,
      collaborateur: "Paul Michel",
      title: "ALGORITHME 404",
      duration: 8.7,
      subtitle: "Erreur humaine",
      description: "Une comédie où une IA tente de comprendre l’humour.",
      category: "Comédie",
      film_url: "https://example.com/films/algorithme-404.mp4",
      poster_url: "https://picsum.photos/seed/film7/600/900",
      outil_Ai: "ChatGPT",
      generate_Ai: "hybrid",
      selected: false,
    },
    {
      candidature_id: 8,
      user_id: 4,
      collaborateur: "Elena Rossi",
      title: "DERNIER CACHE",
      duration: 14.6,
      subtitle: "Mémoire effacée",
      description: "Les souvenirs sont stockés dans le cloud… jusqu’à leur suppression.",
      category: "Thriller",
      film_url: "https://example.com/films/dernier-cache.mp4",
      poster_url: "https://picsum.photos/seed/film8/600/900",
      outil_Ai: "Runway",
      generate_Ai: "full_ai",
      selected: false,
    },
    {
      candidature_id: 9,
      user_id: 5,
      collaborateur: "Hugo Bernard",
      title: "HUMAN.exe",
      duration: 16.0,
      subtitle: "Simulation émotionnelle",
      description: "Une IA tente de simuler des émotions humaines.",
      category: "Science-fiction",
      film_url: "https://example.com/films/human-exe.mp4",
      poster_url: "https://picsum.photos/seed/film9/600/900",
      outil_Ai: "Stable Diffusion",
      generate_Ai: "full_ai",
      selected: true,
    },
    {
      candidature_id: 10,
      user_id: 5,
      collaborateur: "Anna Kowalski",
      title: "PIXELS PERDUS",
      duration: 7.9,
      subtitle: "Fragments visuels",
      description: "Exploration artistique d’erreurs de rendu générées par IA.",
      category: "Art vidéo",
      film_url: "https://example.com/films/pixels-perdus.mp4",
      poster_url: "https://picsum.photos/seed/film10/600/900",
      outil_Ai: "Stable Diffusion",
      generate_Ai: "hybrid",
      selected: false,
    },
  ]);
}
